"""
Generates PDF and Markdown incident reports.
"""

from __future__ import annotations

import io
import textwrap
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.incident import ErrorLog


# ── Helpers ───────────────────────────────────────────────────────────────────

def _fmt_dt(dt: datetime | None) -> str:
    if dt is None:
        return "N/A"
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%b %d, %Y at %I:%M %p UTC")


def _clean(text: str | None) -> str:
    """Strip leading/trailing whitespace; return placeholder if empty."""
    if not text:
        return "N/A"
    return text.strip()


# ── Markdown export ───────────────────────────────────────────────────────────

def generate_markdown(log: "ErrorLog") -> bytes:
    """Return a UTF-8 encoded Markdown incident report."""

    lines: list[str] = []

    def h(level: int, text: str) -> None:
        lines.append(f"{'#' * level} {text}\n")

    def p(text: str) -> None:
        lines.append(f"{text}\n")

    def blank() -> None:
        lines.append("\n")

    def hr() -> None:
        lines.append("---\n")

    # ── Title ──────────────────────────────────────────────────────────────
    h(1, f"Incident Report: {log.service_name}")
    blank()
    p(f"> **Status:** {log.status.replace('_', ' ').title()}  ")
    p(f"> **Service:** `{log.service_name}`  ")
    p(f"> **Workspace:** `{log.workspace_id}`  ")
    p(f"> **Created:** {_fmt_dt(log.timestamp)}  ")

    blank()
    hr()

    # ── Root cause ─────────────────────────────────────────────────────────
    h(2, "Root Cause Analysis")
    blank()
    p(_clean(log.root_cause_analysis))
    blank()
    hr()

    # ── Actionable fix ─────────────────────────────────────────────────────
    h(2, "Actionable Fix")
    blank()
    raw_fix = _clean(log.actionable_fix)
    # If steps are inline (1) ... 2) ...) reformat them onto separate lines
    import re
    formatted_fix = re.sub(r"\s+(\d+\))", r"\n\1", raw_fix)
    p(formatted_fix)
    blank()
    hr()

    # ── Raw stack trace ────────────────────────────────────────────────────
    h(2, "Raw Stack Trace")
    blank()
    lines.append("```\n")
    lines.append(_clean(log.raw_log) + "\n")
    lines.append("```\n")
    blank()
    hr()

    # ── Footer ─────────────────────────────────────────────────────────────
    now = datetime.now(timezone.utc).strftime("%b %d, %Y at %I:%M %p UTC")
    p(f"*Report generated by TraceAgent on {now}*")

    return "".join(lines).encode("utf-8")


# ── PDF export ────────────────────────────────────────────────────────────────

def generate_pdf(log: "ErrorLog") -> bytes:
    """Return raw PDF bytes for the incident report."""

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
        Table, TableStyle, Preformatted,
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    buf = io.BytesIO()

    PAGE_W, PAGE_H = A4
    MARGIN = 20 * mm

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title=f"Incident Report – {log.service_name}",
        author="TraceAgent",
    )

    # ── Colour palette (matches TraceAgent dark theme tokens) ──────────────
    BG_DARK    = colors.HexColor("#0f0f0f")
    ACCENT     = colors.HexColor("#f5a623")     # orange accent
    ERROR_RED  = colors.HexColor("#ef4444")
    SUCCESS_GR = colors.HexColor("#10b981")
    TEXT_PRI   = colors.HexColor("#e5e5e5")
    TEXT_MUT   = colors.HexColor("#6b7280")
    BORDER     = colors.HexColor("#262626")
    MONO_BG    = colors.HexColor("#141414")

    # ── Styles ─────────────────────────────────────────────────────────────
    base = getSampleStyleSheet()

    def style(name, **kw) -> ParagraphStyle:
        return ParagraphStyle(name, **kw)

    S = {
        "title": style(
            "TA_Title",
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=TEXT_PRI,
            leading=28,
            spaceAfter=4,
        ),
        "subtitle": style(
            "TA_Subtitle",
            fontName="Helvetica",
            fontSize=10,
            textColor=TEXT_MUT,
            leading=14,
            spaceAfter=2,
        ),
        "section_header": style(
            "TA_SH",
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=TEXT_PRI,
            leading=16,
            spaceBefore=6,
            spaceAfter=4,
        ),
        "body": style(
            "TA_Body",
            fontName="Helvetica",
            fontSize=9.5,
            textColor=TEXT_PRI,
            leading=15,
            spaceAfter=2,
        ),
        "mono": style(
            "TA_Mono",
            fontName="Courier",
            fontSize=7.5,
            textColor=colors.HexColor("#a3a3a3"),
            leading=11,
            backColor=MONO_BG,
            leftIndent=6,
            rightIndent=6,
        ),
        "label": style(
            "TA_Label",
            fontName="Helvetica-Bold",
            fontSize=7,
            textColor=TEXT_MUT,
            leading=10,
            spaceAfter=1,
        ),
        "meta_val": style(
            "TA_MV",
            fontName="Courier",
            fontSize=8.5,
            textColor=TEXT_PRI,
            leading=12,
        ),
        "footer": style(
            "TA_Footer",
            fontName="Helvetica",
            fontSize=7.5,
            textColor=TEXT_MUT,
            leading=10,
            alignment=TA_CENTER,
        ),
    }

    # ── Page background callback ───────────────────────────────────────────
    def on_page(canvas, doc):
        canvas.saveState()
        canvas.setFillColor(BG_DARK)
        canvas.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)
        # Thin accent line at top
        canvas.setFillColor(ACCENT)
        canvas.rect(0, PAGE_H - 3, PAGE_W, 3, fill=1, stroke=0)
        canvas.restoreState()

    # ── Section header helper ──────────────────────────────────────────────
    def section(label: str, accent_color) -> list:
        return [
            Spacer(1, 8 * mm),
            HRFlowable(
                width="100%",
                thickness=1,
                color=BORDER,
                spaceAfter=4,
            ),
            Paragraph(
                f'<font color="#{accent_color.hexval()[2:]}">'
                f'● </font>{label}',
                S["section_header"],
            ),
            Spacer(1, 2 * mm),
        ]

    # ── Step parser (same logic as frontend) ──────────────────────────────
    import re

    def render_body_text(text: str, is_fix: bool = False) -> list:
        """Split numbered steps onto separate lines for the PDF."""
        flowables = []
        if not text or text == "N/A":
            flowables.append(Paragraph("N/A", S["body"]))
            return flowables

        # Split on inline step numbers e.g. "1) ... 2) ..."
        parts = re.split(r"(?=\b\d+\)\s)", text.strip())
        parts = [p.strip() for p in parts if p.strip()]

        for part in parts:
            # Escape XML special chars for ReportLab
            safe = part.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            num_match = re.match(r"^(\d+)\)\s*", safe)
            if num_match and is_fix:
                num = num_match.group(1)
                body_text = safe[len(num_match.group(0)):]
                step_color = SUCCESS_GR.hexval()[2:]
                para_text = (
                    f'<font name="Helvetica-Bold" color="#{step_color}">{num})</font> {body_text}'
                )
                flowables.append(Paragraph(para_text, S["body"]))
                flowables.append(Spacer(1, 2 * mm))
            else:
                flowables.append(Paragraph(safe, S["body"]))
                flowables.append(Spacer(1, 1.5 * mm))

        return flowables

    # ── Build story ────────────────────────────────────────────────────────
    story = []

    # Header block
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("INCIDENT REPORT", S["label"]))
    story.append(Paragraph(log.service_name, S["title"]))

    # Status badge inline
    status_color = (
        SUCCESS_GR if log.status == "analyzed"
        else ERROR_RED if "fail" in log.status
        else ACCENT
    )
    story.append(
        Paragraph(
            f'<font color="#{status_color.hexval()[2:]}">'
            f'⬤ </font>{log.status.replace("_", " ").upper()}',
            S["subtitle"],
        )
    )
    story.append(Spacer(1, 6 * mm))

    # Metadata table
    meta_rows = [
        ["SERVICE",   log.service_name],
        ["WORKSPACE", log.workspace_id],
        ["CREATED",   _fmt_dt(log.timestamp)],
        ["LOG ID",    str(log.id)],
    ]


    tbl = Table(
        [[Paragraph(k, S["label"]), Paragraph(v, S["meta_val"])] for k, v in meta_rows],
        colWidths=[30 * mm, None],
        hAlign="LEFT",
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), colors.HexColor("#141414")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
         [colors.HexColor("#141414"), colors.HexColor("#1a1a1a")]),
        ("BOX",         (0, 0), (-1, -1), 0.5, BORDER),
        ("INNERGRID",   (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(tbl)

    # Root cause section
    story.extend(section("ROOT CAUSE ANALYSIS", ERROR_RED))
    story.extend(render_body_text(_clean(log.root_cause_analysis), is_fix=False))

    # Actionable fix section
    story.extend(section("ACTIONABLE FIX", SUCCESS_GR))
    story.extend(render_body_text(_clean(log.actionable_fix), is_fix=True))

    # Raw stack trace section
    story.extend(section("RAW STACK TRACE", TEXT_MUT))
    raw_lines = _clean(log.raw_log).split("\n")
    # Limit to first 80 lines in PDF to keep it readable
    preview_lines = raw_lines[:80]
    if len(raw_lines) > 80:
        preview_lines.append(f"... ({len(raw_lines) - 80} more lines truncated)")
    for line in preview_lines:
        safe_line = (
            line
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        story.append(Preformatted(safe_line or " ", S["mono"]))

    # Footer
    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 3 * mm))
    now = datetime.now(timezone.utc).strftime("%b %d, %Y at %I:%M %p UTC")
    story.append(
        Paragraph(f"Generated by TraceAgent  ·  {now}", S["footer"])
    )

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()